// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.id(":r0:")).click();
    driver.findElement(By.id(":r0:")).sendKeys("test@test.com");
    driver.findElement(By.id(":r1:")).click();
    driver.findElement(By.id(":r1:")).sendKeys("test");
    driver.findElement(By.cssSelector(".css-1hjyhw8")).click();
    driver.findElement(By.id(":r1:")).click();
    driver.findElement(By.id(":r1:")).sendKeys("test2");
    driver.findElement(By.cssSelector(".css-1hjyhw8")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id(":r2:")).click();
    driver.findElement(By.id(":r2:")).sendKeys("test@test.com");
    driver.findElement(By.id(":r3:")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id(":r3:")).sendKeys("test");
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
  }
}
