// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class OpenUsersPostsFromUsersProfilePageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void openUsersPostsFromUsersProfilePage() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    driver.findElement(By.id(":r0:")).click();
    driver.findElement(By.id(":r0:")).click();
    driver.findElement(By.id(":r0:")).sendKeys("test@test.com");
    driver.findElement(By.id(":r1:")).click();
    driver.findElement(By.id(":r1:")).sendKeys("test");
    driver.findElement(By.cssSelector(".css-1hjyhw8")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(3) .MuiTypography-root:nth-child(3) > u")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-root:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-root:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".css-pt0p1j-MuiTypography-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiSelect-select > .MuiTypography-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(2) > .MuiBox-root .MuiButtonBase-root:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(2) > .MuiBox-root .MuiButtonBase-root:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,178)");
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(1) .MuiButtonBase-root:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".css-1lfmkxr-MuiTypography-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(1) .MuiButtonBase-root:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(1) .MuiButtonBase-root:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".css-1lfmkxr-MuiTypography-root")).click();
    js.executeScript("window.scrollTo(0,178)");
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(2) > .MuiBox-root .MuiButtonBase-root:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".MuiBox-root:nth-child(3) .MuiPaper-root .MuiTypography-root:nth-child(3)")).click();
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-root:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-root:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
  }
}
